### ISSUE TITLE
No cell level borders

### ISSUE THREAD

**Issue by dwatkinsweb** [chrisglass/xhtml2pdf#225]
I can't set border for specific cells. I have a table that i want to have borders around the cells, except a couple cells at the top left that are left blank so i have top headers and left headers and the body in the middle. I can't override the blank cells to remove the border. I have also tried putting the styles inline on the blank cells using `style="border: 0px none #ffffff;"` and that didnt work either.

```css
#plan_details table {
    border: 1px solid #333333;
    padding-top: 4px; padding-left: 3px; padding-right: 3px; padding-bottom: 3px;
    text-align: center;
}
#plan_details .blank {
    border: 0px none #ffffff;
}
```
